### ISSUE TITLE
How center the element in Angular 5.1 / Error in examples

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-popups#4] opened 2017-12-18 13:32 UTC
Hi,

**How center the element in Angular 5.1:**

With "document.getElementById" it doesn't work to center the dialog box. Also "document" not good for Angular Universal!
Is there a way to get the element over @ViewChild and center the element?

**Error in examples:**

[http://ej2.syncfusion.com/15.4.17/angular/documentation/dialog/getting-started.html#modal-dialog](url)

1. "implements OnInit" -> there is no ngOnInit function.

2. "this.hide" -> hide is not defined  ( public hide: any )

Regards

j.nord

**Comment by gobalakrishnans** [comment] 2017-12-20 14:00
Hi nord,
You can get element over @ViewChild in **“ngAfterViewInit” or “ngOnInit”**, and assign its element as target to the Dialog component. 
We have prepared the sample based on your requirement, and find the plunkr sample link below.

[http://plnkr.co/edit/CLQwoCWIEi9VOBckWUCv?p=preview](http://plnkr.co/edit/CLQwoCWIEi9VOBckWUCv?p=preview)

We will correct the documentation ("document.getElementById" it doesn't work to center the dialog box. Also "document" not good for Angular Universal!) in our end and refresh it in online as soon as possible.

**Query: "implements OnInit" -> there is no ngOnInit function.**

Currently, we have defined the necessary properties on control initialization itself; So, we didn’t use this ngOnInit function in our preview samples. We will consider ngOnInit function in our samples if necessary. We have used the ngOnInit functions in the above provided plunker sample.

**Query: "this.hide" -> hide is not defined ( public hide: any )** 

In the below code example, “this” variable refers to the **Dialog component** (not **AppComponent** class), since the click event is bind to the button inside of the Dialog component. So, we have not included empty declaration for this variable. 

![image](https://user-images.githubusercontent.com/29191202/34210510-0fbe2748-e5bc-11e7-9782-9e075dc1cb6f.png)

If we have misunderstood your requirement, then please provide more information about your problem, or please revert back the provided sample based on your application along with the replication procedure to reproduce the issue at our end.
Regards,
Gobalakrishnan S

**Closed** 2018-02-26 06:39 UTC
